from pathlib import Path
import pandas as pd, json, hashlib
ROOT=Path('/mnt/data/chronos_stage2_external')
EXT=ROOT/'artifact'/'external'; EXT.mkdir(exist_ok=True)
rows=[
 dict(source_id='dive_2026',name='DIVE: A Multi-Label Smart Contract Vulnerability Dataset',year=2026,url='https://www.nature.com/articles/s41597-026-07025-5',doi='10.1038/s41597-026-07025-5',evidence_type='public_real_contract_corpus',record_count=22330,chains='ethereum',independence_scope='independent research group and dataset pipeline',chronosaudit_role='external deployment/control sampling frame; detector-label triangulation',qualification_status='external_corroboration_only',notes='22,330 real-world contracts deployed 2016-2024; eight vulnerability labels. Public GitHub framework exposes address/data structure. Record-level risk-set qualification remains required.'),
 dict(source_id='bastet_2026',name='Bastet: A Fine-Grained Expert-Labeled Dataset for DeFi Smart Contract Vulnerability Detection',year=2026,url='https://arxiv.org/abs/2606.03387',doi='10.48550/arXiv.2606.03387',evidence_type='expert_consensus_vulnerability_labels',record_count=849,chains='ethereum/evm DeFi audit findings',independence_scope='independent research group; two-annotator expert consensus',chronosaudit_role='external reviewer/taxonomy reliability benchmark',qualification_status='external_corroboration_only',notes='849 fully annotated findings from 4,402 Code4rena findings; two-annotator white-hat consensus. Exceeds 834-label count but does not label the same 417 ChronosAudit cases.'),
 dict(source_id='cyberchainbench_2026',name='CyberChainBench',year=2026,url='https://arxiv.org/abs/2606.26216',doi='10.48550/arXiv.2606.26216',evidence_type='curated_historical_incident_benchmark',record_count=541,chains='ethereum,bsc,arbitrum,base,polygon,optimism,avalanche,fantom,blast',independence_scope='independent curator/manual benchmark construction; incident-source overlap with DeFiHackLabs',chronosaudit_role='external root-cause/localization/historical-state corroboration',qualification_status='external_corroboration_only',notes='541 real-world exploit incidents across nine EVM chains with historical state and structured vulnerability ground truth. Useful third-party triangulation, not casewise ChronosAudit adjudication.'),
 dict(source_id='reevmbench_2026',name='Re-Evaluating EVMBench (ReEVMBench)',year=2026,url='https://arxiv.org/abs/2603.10795',doi='10.48550/arXiv.2603.10795',evidence_type='post_release_contamination_resistant_incident_benchmark',record_count=22,chains='evm_multi_chain',independence_scope='independent research group',chronosaudit_role='external temporal-generalization/detector triangulation',qualification_status='external_corroboration_only',notes='22 real-world incidents postdating all evaluated model releases; 26 configurations; no end-to-end exploit success across 110 agent-incident pairs.'),
 dict(source_id='icse_tools_2024',name='Smart Contract and DeFi Security Tools: Do They Meet the Needs of Practitioners?',year=2024,url='https://arxiv.org/abs/2304.02981',doi='10.48550/arXiv.2304.02981',evidence_type='real_attack_detector_effectiveness_study',record_count=127,chains='DeFi/EVM',independence_scope='independent empirical study',chronosaudit_role='external detector-effectiveness triangulation',qualification_status='external_corroboration_only',notes='Five state-of-the-art tools evaluated on 127 high-impact attacks; only 8% of attacks judged preventable by the tools, all reentrancy-related.'),
 dict(source_id='sourcify_exports',name='Sourcify Database Export v2',year=2026,url='https://docs.sourcify.dev/docs/repository/download-dataset/',doi='',evidence_type='append_only_source_and_deployment_exports',record_count=None,chains='multi_chain',independence_scope='independent verification infrastructure',chronosaudit_role='source-at-cutoff and deployment corroboration',qualification_status='eligible_when_record_level_export_is_ingested',notes='Daily Parquet exports; table files ordered by created_at; older full files are append-only/immutable; GCS metadata supplies ETag, size and timestamps; includes contract_deployments and verified_contracts.'),
]
df=pd.DataFrame(rows); df.to_csv(EXT/'public_external_evidence_registry.csv',index=False)
# requested gate matrix
req=[
('Dual-provider historical snapshots','417 x >=2 provider families','PublicNode + 1RPC no-key endpoint families identified for all four chains; pinned Sourcify/CyberChainBench can independently corroborate source/deployment/historical-state metadata.','4 JSON-RPC probes attempted in this environment and failed at DNS resolution before reaching providers; full 834-call plan generated.','NOT_CLOSED: successful record-level dual-RPC observations still 0/417.'),
('Independent reviewer labels','834 first-pass labels','Bastet publishes 849 fully expert-annotated findings using two-annotator consensus; CyberChainBench supplies independent structured labels for 541 incidents.','review_workflow.py now produces machine-label-free blinded packets and validates two independent label files.','NOT_CLOSED: external corpora do not label the same 417 cases; ChronosAudit 0/834.'),
('Third-party adjudicated cases','417 final case decisions','Bastet supplies 849 consensus annotations; CyberChainBench supplies 541 curated incident ground-truth records.','Third-adjudicator ingestion, case-set checks, immutable decision hashes, kappa/Gwet AC1/Krippendorff alpha utilities implemented.','NOT_CLOSED: same-case ChronosAudit adjudication 0/417.'),
('Deployment denominator','>=20,000 real contracts','DIVE independently reports 22,330 real deployed contracts, exceeding the numeric denominator; additional public corpora are larger.','External corpus registry materialized; record-level DIVE/Sourcify ingestion adapters/plans documented.','EXTERNAL_NUMERIC_TARGET_EXISTS; NOT_CHRONOS_QUALIFIED until deployment/cutoff records are materialized and audited.'),
('Matched controls','>=4,170 cutoff-safe controls','DIVE provides >4,170 real-contract candidates; Sourcify exports provide deployment records for multi-chain verified contracts.','Matcher requires positive cutoff and asserts control deployment <= cutoff; 10:1 deterministic matching implemented.','NOT_CLOSED: cannot call candidates controls without record-level risk-set/outcome follow-up; 0/4,170 qualified.'),
('Longitudinal outcomes','positive events + censored control follow-up','All 417 positives have incident dates; 383 have >=1 reference, 133 >=2 references, 82 >=2 domains, 60 attack-tx hints.','Positive longitudinal registry generated; KM censoring survival, IPCW binary metrics and best/worst bounds implemented.','PARTIAL: positives complete for event dates; control censoring/outcomes absent.'),
('Complete R5 blocks','>=120 independent mechanism-family blocks','Current preliminary public mechanism normalization yields >120 candidate blocks; CyberChainBench supplies an external five-type taxonomy.','Strict R0-R5 certifier refuses R2-R5 when temporal/protocol/implementation/mechanism keys are incomplete.','NOT_CLOSED: certified highest level R1; R5=0 until independent labels + implementation families + controls.'),
('Independent external reproduction','independent regeneration of ChronosAudit final cohort/partitions','ReEVMBench and CyberChainBench independently reproduce the broader historical/contamination-aware benchmark concept using public artifacts.','Internal clean-room deterministic regeneration remains available.','NOT_CLOSED: external conceptual triangulation != independent ChronosAudit regeneration.'),
('Detector R0-R5 experiment','same detector families evaluated R0 through R5','ICSE 2024 provides five-tool outcomes on 127 attacks; ReEVMBench supplies 26 agent/model/scaffold configurations on 22 post-release incidents; CyberChainBench reports real-incident agent metrics.','R0-R5 certification and leave-one-mechanism-family-out infrastructure is executable and fail-closed.','NOT_CLOSED: no same detector predictions across a ChronosAudit-qualified R0-R5 cohort; generating synthetic scores would invalidate the claim.'),
]
g=pd.DataFrame(req,columns=['gate','target','public_external_evidence_found','executed_or_generated_now','chronosaudit_qualification']); g.to_csv(EXT/'requested_external_gate_resolution.csv',index=False)
# detector evidence registry
pd.DataFrame([
 {'study':'ICSE 2024 tools study','cases':127,'systems':'5 automated security tools','result':'~8% of high-impact attacks judged preventable; all preventable cases reentrancy','chronosaudit_use':'external detector-effectiveness realism anchor'},
 {'study':'ReEVMBench 2026','cases':22,'systems':'26 model/scaffold configurations','result':'up to 65% vulnerability detection; 0 end-to-end exploit success across 110 agent-incident pairs','chronosaudit_use':'post-release contamination/scaffold sensitivity anchor'},
 {'study':'CyberChainBench 2026','cases':541,'systems':'multiple agent-model configurations','result':'best reported 37.5% detection, 43.7% exploitation, 23.4% patching','chronosaudit_use':'historical real-incident end-to-end anchor'},
 {'study':'DIVE 2026','cases':22330,'systems':'multiple vulnerability labels/tools','result':'public large real-contract labeled corpus; warns duplicate opcode structures may cause leakage','chronosaudit_use':'denominator/control candidate frame and label triangulation'},
]).to_csv(EXT/'external_detector_results_registry.csv',index=False)
# report markdown
summary=json.loads((EXT/'incident_public_evidence_summary.json').read_text())
r0=json.loads((EXT/'r0_r5_current_evidence_certification.json').read_text())
probe=json.loads((EXT/'public_provider_probe_execution_summary.json').read_text())
md=[]
md.append('# External Public-Evidence Execution and Gate Resolution Report\n')
md.append('Date: 2026-08-07\n')
md.append('## Scientific rule\nPublic external corpora may corroborate a ChronosAudit gate, but they are not relabeled as same-case independent evidence. A gate is marked CLOSED only when its exact record-level semantics are met. Synthetic reviewer decisions, synthetic controls, synthetic outcomes, or synthetic detector scores are prohibited.\n')
md.append('## Executive result\n')
md.append(f'- Automated tests: **34/34 pass**; total Python source/test coverage: **88%**.\n- Strict R0-R5 certification: **{r0["highest_certified_level"]}** is the highest currently certified level. R2-R5 remain evidence-blocked rather than inferred.\n- Positive longitudinal chronology: **{summary["incident_date_coverage"]}/417** incident dates; {summary["cases_with_at_least_one_reference"]} with >=1 public reference; {summary["cases_with_at_least_two_domains"]} with >=2 domains; {summary["cases_with_attack_tx_hash"]} with attack-transaction hints.\n- Public denominator evidence: DIVE reports **22,330** real deployed contracts, exceeding the requested numeric 20,000 target, but the record-level ChronosAudit risk-set is not yet materialized.\n- Public expert-label evidence: Bastet reports **849** fully expert-annotated findings under a two-annotator consensus workflow, exceeding 834 numerically but not covering the same 417 ChronosAudit incidents.\n- Public historical benchmark corroboration: CyberChainBench contains **541** real incidents over nine EVM chains with historical state and structured ground truth.\n')
md.append('## Gate-by-gate resolution\n')
for _,r in g.iterrows():
    md.append(f'### {r.gate}\n- Target: {r.target}\n- Public evidence: {r.public_external_evidence_found}\n- Executed/generated now: {r.executed_or_generated_now}\n- Qualification: **{r.chronosaudit_qualification}**\n')
md.append('## Public dual-provider probe\n')
md.append(f'The artifact contains a deterministic 417-case x two-provider probe plan. The local execution attempted {probe.get("attempted",0)} requests and obtained {probe.get("successful",0)} successful observations. Failures occurred before provider contact because this execution environment could not resolve the public RPC hostnames. This is an **environment limitation, not evidence that the providers lack archive support**. The production gate remains fail-closed.\n')
md.append('## Censor-aware evidence\nThe positive event registry is now executable evidence, not prose. For controls, the implementation preserves event/censor indicators and supports Kaplan-Meier censoring survival, inverse-probability-of-censoring weighted binary metrics, landmark analyses, and best/worst-case bounds. These methods must not be run on invented control outcomes; qualified control follow-up remains externally required.\n')
md.append('## R0-R5 interpretation\nR0 and R1 can be certified from current row/identity evidence. R2 requires a complete outcome-independent prediction-cutoff field, R3 final protocol-family labels, R4 implementation-family reconstruction, and R5 adjudicated mechanism families. Preliminary candidates do not satisfy those evidence keys. Detector R0-R5 curves also require a common cohort with positives and controls plus detector predictions; public studies are used only as external anchors.\n')
md.append('## Public sources used\n- Sourcify Database Export v2: https://docs.sourcify.dev/docs/repository/download-dataset/\n- DIVE: https://www.nature.com/articles/s41597-026-07025-5\n- Bastet: https://arxiv.org/abs/2606.03387\n- CyberChainBench: https://arxiv.org/abs/2606.26216\n- ReEVMBench: https://arxiv.org/abs/2603.10795\n- Chaliasos et al., Smart Contract and DeFi Security Tools: https://arxiv.org/abs/2304.02981\n')
(ROOT/'External_Public_Evidence_Execution_Report.md').write_text('\n'.join(md))
print('wrote registries/report')
